import { useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { categoriesApi, type CategoryApi } from "../../../api/categories.api";

function CategoryForm({ category, mode }: { category?: CategoryApi; mode: "create" | "edit" }) {
  const navigate = useNavigate(); const fileInputRef = useRef<HTMLInputElement>(null); const [name, setName] = useState(category?.name ?? ""); const [description, setDescription] = useState(category?.description ?? ""); const [imageUrl, setImageUrl] = useState(category?.imageUrl ?? ""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { setSaving(true); setError(""); const body = { name: name.trim(), description: description.trim() || undefined, imageUrl: imageUrl || undefined }; category ? await categoriesApi.update(category.id, body) : await categoriesApi.create(body); navigate("/categories"); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to save category."); } finally { setSaving(false); } };
  return <form className="category-form" onSubmit={submit}><div className="category-form-columns"><div className="category-information"><h3>Category Information</h3><label>Category Name <b>*</b><input required value={name} onChange={(e) => setName(e.target.value)} /></label><label>Description<textarea value={description} onChange={(e) => setDescription(e.target.value)} /></label></div><div className="category-image-column"><h3>Category Image URL</h3><label>Image URL<input value={imageUrl} onChange={(e) => setImageUrl(e.target.value)} placeholder="https://..." /></label><button type="button" className="upload-box" onClick={() => fileInputRef.current?.click()}><strong>Preview local image</strong></button><input ref={fileInputRef} className="hidden-file-input" type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => { const file = event.target.files?.[0]; if (file) setImageUrl(URL.createObjectURL(file)); }} />{imageUrl && <div className="image-preview"><img src={imageUrl} alt="Category preview" /><button type="button" onClick={() => setImageUrl("")}>Remove</button></div>}</div></div>{error && <p role="alert">{error}</p>}<div className="form-actions"><button type="button" onClick={() => navigate(-1)}>Cancel</button><button className="primary-button" disabled={saving} type="submit">{saving ? "Saving..." : mode === "create" ? "Save Category" : "Save Changes"}</button></div></form>;
}
export default CategoryForm;
