import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { customersApi, type CustomerApi, type CustomerUpsert } from "../../../api/customers.api";

function CustomerForm({ customer, mode }: { customer?: CustomerApi; mode: "create" | "edit" }) {
  const navigate = useNavigate();
  const [form, setForm] = useState<CustomerUpsert>({ fullName: customer?.fullName ?? "", phone: customer?.phone ?? "", email: customer?.email ?? "", status: customer?.status ?? "Active", tier: customer?.tier ?? "Regular", gender: customer?.gender ?? "Male", address: customer?.address ?? "", dateOfBirth: customer?.dateOfBirth?.slice(0, 10) ?? "", notes: customer?.notes ?? "" });
  const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const update = <K extends keyof CustomerUpsert>(key: K, value: CustomerUpsert[K]) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { setSaving(true); setError(""); customer ? await customersApi.update(customer.id, form) : await customersApi.create(form); navigate("/customers"); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to save customer."); } finally { setSaving(false); } };
  return <form className="customer-form" onSubmit={submit}><div className="customer-form-grid"><label className="field-group"><span>Full Name</span><input required value={form.fullName} onChange={(e) => update("fullName", e.target.value)} /></label><label className="field-group"><span>Customer Type</span><select value={form.tier} onChange={(e) => update("tier", e.target.value as CustomerUpsert["tier"])}><option>Regular</option><option>VIP</option><option>New</option></select></label><label className="field-group"><span>Phone Number</span><input required value={form.phone} onChange={(e) => update("phone", e.target.value)} /></label><label className="field-group"><span>Gender</span><select value={form.gender} onChange={(e) => update("gender", e.target.value as CustomerUpsert["gender"])}><option>Male</option><option>Female</option><option>Other</option></select></label><label className="field-group"><span>Email</span><input type="email" value={form.email} onChange={(e) => update("email", e.target.value)} /></label><label className="field-group"><span>Address</span><input value={form.address} onChange={(e) => update("address", e.target.value)} /></label><label className="field-group"><span>Date of Birth</span><input type="date" value={form.dateOfBirth} onChange={(e) => update("dateOfBirth", e.target.value)} /></label><label className="field-group full-width"><span>Notes</span><textarea value={form.notes} onChange={(e) => update("notes", e.target.value)} /></label></div>{error && <p role="alert">{error}</p>}<div className="customer-form-actions"><button className="secondary-button" type="button" onClick={() => navigate(-1)}>Cancel</button><button className="primary-button" disabled={saving} type="submit">{saving ? "Saving..." : mode === "create" ? "Save Customer" : "Update Customer"}</button></div></form>;
}
export default CustomerForm;
