import { useState } from "react";
import ConfirmDeleteModal from "../common/ConfirmDeleteModal";
import "./Tables.css";
type TableStatus = "Available" | "Occupied" | "Reserved";
type RestaurantTable = { id: number; seats: number; status: TableStatus };
const STORAGE_KEY = "restaurant-tables";
const defaults: RestaurantTable[] = [{ id: 1, seats: 2, status: "Available" }, { id: 2, seats: 4, status: "Occupied" }, { id: 3, seats: 4, status: "Available" }, { id: 4, seats: 6, status: "Available" }, { id: 5, seats: 4, status: "Occupied" }, { id: 6, seats: 2, status: "Available" }, { id: 7, seats: 4, status: "Available" }, { id: 8, seats: 6, status: "Reserved" }];
function TablesPage() { const [tables, setTables] = useState<RestaurantTable[]>(() => { const saved = localStorage.getItem(STORAGE_KEY); return saved ? JSON.parse(saved) as RestaurantTable[] : defaults; }); const [selected, setSelected] = useState<RestaurantTable>(tables[0] ?? defaults[0]); const [editing, setEditing] = useState<RestaurantTable | null>(null); const [deleting, setDeleting] = useState<RestaurantTable | null>(null); const save = (next: RestaurantTable[]) => { setTables(next); localStorage.setItem(STORAGE_KEY, JSON.stringify(next)); }; const saveTable = (draft: RestaurantTable) => { const exists = tables.some((table) => table.id === draft.id); const next = exists ? tables.map((table) => table.id === draft.id ? draft : table) : [...tables, draft]; save(next); setSelected(draft); setEditing(null); }; return <section className="tables-page"><div className="tables-heading"><div><p className="eyebrow">Floor management</p><h1>Tables</h1><p>See table availability and current orders at a glance.</p></div><button className="primary-button" onClick={() => setEditing({ id: Math.max(0, ...tables.map((table) => table.id)) + 1, seats: 2, status: "Available" })}>＋ Add Table</button></div><div className="table-layout"><div className="table-grid">{tables.map((table) => <article onClick={() => setSelected(table)} className={`restaurant-table ${table.status.toLowerCase()} ${selected.id === table.id ? "selected" : ""}`} key={table.id}><span className="table-icon">♜</span><strong>Table {table.id}</strong><small>{table.seats} Seats</small><em>{table.status}</em></article>)}</div><aside className="table-detail"><div><p className="eyebrow">Selected table</p><h2>Table {selected.id}</h2><span className={`order-status ${selected.status.toLowerCase()}`}>● {selected.status}</span></div><hr /><p className="detail-label">TABLE DETAILS</p><strong>{selected.seats} Seats <span>{selected.status}</span></strong><p>{selected.status === "Occupied" ? "Current order #10025" : "No active order"}</p><button className="primary-button" onClick={() => setEditing(selected)}>Edit Table</button><button onClick={() => setDeleting(selected)} className="delete-table">Delete Table</button></aside></div>{editing && <TableForm table={editing} usedIds={tables.filter((table) => table.id !== editing.id).map((table) => table.id)} onClose={() => setEditing(null)} onSave={saveTable} />}{deleting && <ConfirmDeleteModal itemName={`Table ${deleting.id}`} itemType="Table" onCancel={() => setDeleting(null)} onConfirm={() => { const next = tables.filter((table) => table.id !== deleting.id); save(next); setSelected(next[0] ?? { id: 0, seats: 0, status: "Available" }); setDeleting(null); }} />}</section>; }
function TableForm({ table, usedIds, onClose, onSave }: { table: RestaurantTable; usedIds: number[]; onClose: () => void; onSave: (table: RestaurantTable) => void }) { const [id, setId] = useState(String(table.id)); const [seats, setSeats] = useState(String(table.seats)); const [status, setStatus] = useState<TableStatus>(table.status); return <div className="modal-backdrop"><form className="create-order-modal" onSubmit={(event) => { event.preventDefault(); const nextId = Number(id); if (!nextId || usedIds.includes(nextId)) return; onSave({ id: nextId, seats: Number(seats) || 1, status }); }}><div className="modal-title"><div><p className="eyebrow">Floor management</p><h2>{table.id && !usedIds.includes(table.id) ? "Edit Table" : "Create Table"}</h2></div><button type="button" className="icon-button" onClick={onClose}>×</button></div><label>Table number<input required type="number" min="1" value={id} onChange={(event) => setId(event.target.value)} /></label><label>Number of seats<input required type="number" min="1" value={seats} onChange={(event) => setSeats(event.target.value)} /></label><label>Status<select value={status} onChange={(event) => setStatus(event.target.value as TableStatus)}>{(["Available", "Occupied", "Reserved"] as TableStatus[]).map((value) => <option key={value}>{value}</option>)}</select></label><div className="modal-actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary-button" type="submit">Save Table</button></div></form></div>; }
export default TablesPage;
