import { api, query } from "./client";
export type RestaurantTableApi = { id: number; tableNumber: string; seatCapacity: number; area: string; status: "Available" | "Occupied" | "Reserved" };
export type OrderItemApi = { id?: number; itemName: string; variant?: string; quantity: number; unitPrice: number; lineTotal?: number };
export type KitchenTicketApi = { id: number; restaurantOrderId: number; ticketNumber: number; customerName: string; orderType: OrderApi["orderType"]; restaurantTableId?: number; tableNumber?: string; status: "Pending" | "Preparing" | "Ready"; specialInstructions?: string; createdAtUtc: string; items: Array<{ id: number; itemName: string; variant?: string; quantity: number }> };
export type PaymentMethod = "Cash" | "UPI" | "Split";
export type PaymentDetails = { paymentMethod: PaymentMethod; cashAmount: number; upiAmount: number };
export type OrderApi = { id: number; customerName: string; orderType: "DineIn" | "Takeaway" | "Delivery"; status: "Pending" | "Preparing" | "Ready" | "Completed" | "Cancelled"; restaurantTableId?: number; tableNumber?: string; subtotal: number; discountPercent: number; discountAmount: number; cgstPercent: number; cgstAmount: number; sgstPercent: number; sgstAmount: number; taxAmount: number; totalAmount: number; paymentMethod?: PaymentMethod; cashAmount?: number; upiAmount?: number; specialInstructions?: string; createdAtUtc: string; completedAtUtc?: string; items: OrderItemApi[] };
export const ordersApi = {
  listTables: () => api<RestaurantTableApi[]>("/api/tables"), createTable: (body: Omit<RestaurantTableApi, "id">) => api<RestaurantTableApi>("/api/tables", { method: "POST", body: JSON.stringify(body) }), updateTable: (id: number, body: Omit<RestaurantTableApi, "id">) => api<RestaurantTableApi>(`/api/tables/${id}`, { method: "PUT", body: JSON.stringify(body) }), deleteTable: (id: number) => api<boolean>(`/api/tables/${id}`, { method: "DELETE" }),
  list: (status?: string, fromDateUtc?: string) => api<OrderApi[]>(`/api/orders${query({ status, fromDateUtc })}`), get: (id: number) => api<OrderApi>(`/api/orders/${id}`), create: (body: { customerName: string; orderType: OrderApi["orderType"]; restaurantTableId?: number; specialInstructions?: string; items: OrderItemApi[] }) => api<OrderApi>("/api/orders", { method: "POST", body: JSON.stringify(body) }), update: (id: number, body: { customerName: string; orderType: OrderApi["orderType"]; restaurantTableId?: number; specialInstructions?: string; items: OrderItemApi[] }) => api<OrderApi>(`/api/orders/${id}`, { method: "PUT", body: JSON.stringify(body) }), updateStatus: (id: number, status: OrderApi["status"]) => api<OrderApi>(`/api/orders/${id}/status`, { method: "PATCH", body: JSON.stringify(status) }), completePayment: (id: number, details: PaymentDetails) => api<OrderApi>(`/api/orders/${id}/payment`, { method: "POST", body: JSON.stringify(details) }), remove: (id: number) => api<boolean>(`/api/orders/${id}`, { method: "DELETE" }),
  listKitchenTickets: () => api<KitchenTicketApi[]>("/api/orders/kitchen-tickets"), updateKitchenTicketStatus: (id: number, status: KitchenTicketApi["status"]) => api<KitchenTicketApi>(`/api/kitchen-tickets/${id}/status`, { method: "PATCH", body: JSON.stringify({ status }) }),
};
