import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { categoriesApi, type CategoryApi } from "../../../api/categories.api";
import { menuItemsApi, type MenuItemUpsert } from "../../../api/menu-items.api";
import "../MenuItems.css";

function AddMenuItemPage() {
  const navigate = useNavigate(); const { id } = useParams(); const [categories, setCategories] = useState<CategoryApi[]>([]); const [form, setForm] = useState<MenuItemUpsert>({ code: "", name: "", categoryId: 0, description: "", price: 0, preparationTimeMinutes: 0, calories: undefined, ingredients: "", status: "Active", dietaryType: "Veg", imageUrl: "", tags: "", optionGroups: [] }); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { categoriesApi.list().then((data) => { setCategories(data); setForm((current) => current.categoryId ? current : { ...current, categoryId: data[0]?.id ?? 0 }); }).catch((e: unknown) => setError(e instanceof Error ? e.message : "Unable to load categories.")); }, []);
  useEffect(() => { if (id) menuItemsApi.get(Number(id)).then((item) => setForm({ code: item.code, name: item.name, categoryId: item.categoryId, description: item.description, price: item.price, preparationTimeMinutes: item.preparationTimeMinutes, calories: item.calories, ingredients: item.ingredients, status: item.status, dietaryType: item.dietaryType, imageUrl: item.imageUrl, tags: item.tags, optionGroups: item.optionGroups })).catch((e: unknown) => setError(e instanceof Error ? e.message : "Unable to load menu item.")); }, [id]);
  const update = <K extends keyof MenuItemUpsert>(key: K, value: MenuItemUpsert[K]) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); try { setSaving(true); setError(""); id ? await menuItemsApi.update(Number(id), form) : await menuItemsApi.create(form); navigate("/menu"); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save menu item."); } finally { setSaving(false); } };
  return <section className="menu-item-page"><div className="menu-item-heading"><div><div className="breadcrumb"><Link to="/dashboard">Home</Link><span>/</span><Link to="/menu">Menu</Link><span>/</span><strong>{id ? "Edit Menu Item" : "Add Menu Item"}</strong></div><h1>{id ? "Edit Menu Item" : "Add New Menu Item"}</h1><p>Create or update a menu item.</p></div></div><form className="menu-item-form" onSubmit={submit}><div className="menu-item-top-grid"><section className="menu-panel basic-panel"><h2>Basic Information</h2><label>Item Code <b>*</b><input required value={form.code} onChange={(e) => update("code", e.target.value)} /></label><label>Item Name <b>*</b><input required value={form.name} onChange={(e) => update("name", e.target.value)} /></label><label>Category <b>*</b><select required value={form.categoryId} onChange={(e) => update("categoryId", Number(e.target.value))}>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="wide-field">Description <b>*</b><textarea required value={form.description} onChange={(e) => update("description", e.target.value)} /></label><label>Price <b>*</b><input required type="number" min="0" step="0.01" value={form.price} onChange={(e) => update("price", Number(e.target.value))} /></label><label>Status<select value={form.status} onChange={(e) => update("status", e.target.value as MenuItemUpsert["status"])}><option>Active</option><option>Inactive</option></select></label><label>Dietary Type<select value={form.dietaryType} onChange={(e) => update("dietaryType", e.target.value as MenuItemUpsert["dietaryType"])}><option>Veg</option><option>Non-Veg</option></select></label></section><section className="menu-panel additional-panel"><h2>Additional Details</h2><label>Image URL<input value={form.imageUrl ?? ""} onChange={(e) => update("imageUrl", e.target.value)} /></label><label>Preparation Time (minutes)<input type="number" min="0" value={form.preparationTimeMinutes} onChange={(e) => update("preparationTimeMinutes", Number(e.target.value))} /></label><label>Calories<input type="number" min="0" value={form.calories ?? ""} onChange={(e) => update("calories", e.target.value ? Number(e.target.value) : undefined)} /></label><label>Ingredients<textarea value={form.ingredients ?? ""} onChange={(e) => update("ingredients", e.target.value)} /></label><label>Tags<input value={form.tags ?? ""} onChange={(e) => update("tags", e.target.value)} placeholder="Comma-separated tags" /></label></section></div>{error && <p role="alert">{error}</p>}<div className="menu-form-actions"><button type="button" onClick={() => navigate(-1)}>Cancel</button><button className="primary-button" disabled={saving} type="submit">{saving ? "Saving..." : "Save Menu Item"}</button></div></form></section>;
}
export default AddMenuItemPage;
